### ISSUE TITLE
Cannot install to theos

### ISSUE THREAD

**Issue by Shade-Zepheri** [akemin-dayo/KarenPrefs#2]
When I run make install to theos, i get this error https://ghostbin.com/paste/rcgas Is this an issue on my end or on yours?

**Comment by akemin-dayo** [comment]
The linker appears to be unable to link against `PSSpecifier` and `PSSwitchTableCell`. What iOS SDK are you using and do you have a `PrivateFrameworks` folder inside that SDK?

**Comment by Shade-Zepheri** [comment]
I am using the 9.3 sdk from here https://github.com/theos/sdks and it appears to have all the privateframeworks

**Comment by akemin-dayo** [comment]
Hm, interesting. Which Xcode version are you using?

**Comment by Shade-Zepheri** [comment]
Latest on macOS Sierra…could that be the issue?

**Comment by akemin-dayo** [comment]
Er, if you're using the latest Xcode (which is 8.x), then I think you'd be using the iOS 10 SDK. Last time I tried, I never got Xcode 8 to cooperate with an older SDK :/

If you can, try installing Xcode 7.3.1 and see what happens.

(I haven't had time to test anything I've written on Xcode 8/iOS 10 SDK yet, so...)

**Comment by Shade-Zepheri** [comment]
I get this error now https://ghostbin.com/paste/j25rc probably because its missing the default 9.3 sdk is missing PrivateFrameworks. But when I put the private frameworks folder from https://github.com/theos/sdks I get the same error https://ghostbin.com/paste/64hb4

**Comment by akemin-dayo** [comment]
Huh, that's interesting. I just tried compiling KarenPrefs with the latest Xcode 8 version from the App Store, using `iPhoneOS10.0.sdk` and everything was fine.
1. Are you sure you're using the most recent Theos version? Run `make update-theos` while in the `KarenPrefs` directory to be sure.
2. There should be a large number of frameworks inside `iPhoneOS10.0.sdk/System/Library/PrivateFrameworks` — if they are not present, then copy them from `iPhoneOS9.2.sdk` available from here: https://sdks.website/

**Comment by Shade-Zepheri** [comment]
I'll reinstall theos and install Xcode 8 w/ iOS 10 sdk and report back tonight

**Comment by akemin-dayo** [comment]
Closed due to inactivity. Reopen if still needed/relevant.
