### ISSUE TITLE
Cannot build libkarenprefs using Theos

### ISSUE THREAD

**Issue by mitchelhussack** [akemin-dayo/KarenPrefs#3]
I get these errors when trying to install to Theos:

make[3]: *** [/Users/mitchelhussack/KarenPrefs/.theos/obj/armv7/libkarenprefs.dylib] Error 1
make[2]: *** [/Users/mitchelhussack/KarenPrefs/.theos/obj/armv7/libkarenprefs.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [libkarenprefs.all.library.variables] Error 2

Any reason why this may be happening?

**Comment by akemin-dayo** [comment]
I'd need more information in order to tell what exactly is happening there.

As a general troubleshooting step, make sure you have the latest Theos installed. Run `make update-theos` to be sure.

**Comment by akemin-dayo** [comment]
Closed due to inactivity — feel free to reopen if still needed.
